spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://152.136.119.151:3301/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
      slave:
        url: jdbc:mysql://152.136.119.151:3302/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    stat-view-servlet: #访问监控网页的登录用户名和密码
      login-username: druid
      login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml